
# Iteration { }  



A purrr [tutorial](https://jennybc.github.io/purrr-tutorial/index.html ) 



<!-- ======================================================= -->
## Overview { }

Keep the title of this section as "Overview".  
This tab should include:  

* Textual overview of the purpose of this page  
* Small image showing outputs   



<!-- ======================================================= -->
## Preparation { }

Keep the title of this section as "Preparation".  
Data preparation steps such as:  

* Loading dataset  
* Adding or changing variables  
* melting, pivoting, grouping, etc.   

<!-- ======================================================= -->
### sub-tab 1 { }

Can be used to separate major steps of data preparation. Re-name as needed


<!-- ======================================================= -->
### sub-tab 2 { }

Can be used to separate major steps of data preparation. Re-name as needed.



<!-- ======================================================= -->
## Option 1 { }

This tab can be renamed. 
This tab should demonstrate execution of the task using recommended package/approach. For example, using a package customized for this task where the execution is simple and fast but perhaps less customizable. For example using *incidence* package to create an epicurve.


<!-- ======================================================= -->
### Option 1 sub-tab { }

Sub-tabs if necessary. Re-name as needed.



<!-- ======================================================= -->
## Option 2 { }

This tab can be re-named. 
This tab should demonstrate execution of the task a more standard/core package (e.g. ggplot2, or base R) that allows for more flexibility in the output or more package stability. For example, showing how to create an epicurve using *ggplot2*. 


<!-- ======================================================= -->
### Option 2 sub-tab { }

Sub-tabs if necessary. Re-name as needed.



<!-- ======================================================= -->
## Resources { }

This tab should stay with the name "Resources".
Links to other online tutorials or resources.



