# الأخطاء الشائعة  

تتضمن هذه الصفحة قائمة مستمرة للأخطاء الشائعة وتقترح حلولًا لحلها.  


## تفسير رسائل الخطأ  

يمكن أن تكون رسائل الخطأ في R غامضة في بعض الأحيان، لذا جوجل هو صديقك. ابحث عن رسالة الخطأ باستخدام "R" وابحث عن المشاركات الأخيرة في [StackExchange.com](StackExchange.com), [stackoverflow.com](stackoverflow.com), [community.rstudio.com](community.rstudio.com), تويتر (#rstats)، ومنتديات أخرى تستخدمها المبرمجون لطرح الأسئلة والإجابات. حاول العثور على مشاركات حديثة قد حلت مشاكل مماثلة.  

إذا لم تتمكن من العثور على إجابة لمشكلتك بعد البحث الكثير، فكر في إنشاء *مثال قابل لإعادة الإنتاج* ("reprex") ونشر السؤال بنفسك. انظر الصفحة حول [الحصول على مساعدة](help.qmd) للحصول على نصائح حول كيفية إنشاء ونشر مثال قابل لإعادة الإنتاج إلى المنتديات.  


## الأخطاء الشائعة  

أدناه، نقدم بعض الأخطاء الشائعة والتفسيرات/الحلول المحتملة. بعضها مأخوذ من Noam Ross الذي قام بتحليل أكثر المشاركات شيوعًا على Stack Overflow حول رسائل الخطأ في R (انظر التحليل [هنا](https://github.com/noamross/zero-dependency-problems/blob/master/misc/stack-overflow-common-r-errors.md))  


### أخطاء الطباعة {.unnumbered}  

```  
Error: unexpected symbol in:
"  geom_histogram(stat = "identity")+  
  tidyquant::geom_ma(n=7, size = 2, color = "red" lty"  
```  
إذا رأيت "unexpected symbol"، تحقق من وجود الفواصل المفقودة  


### أخطاء الحزمة {.unnumbered}  

```  
could not find function "x"...  
```  
هذا يعني على الأرجح أنك كتبت اسم الدالة بشكل غير صحيح، أو نسيت تثبيت أو تحميل حزمة.  


```  
Error in select(data, var) : unused argument (var)  
```  
تعتقد أنك تستخدم `dplyr::select()` ولكن الدالة `select()` قد تم حجبها بواسطة `MASS::select()` - حدد `dplyr::` أو أعد ترتيب تحميل الحزم بحيث يكون dplyr بعد جميع الآخرين.

تنبع أخطاء الحجب الشائعة الأخرى من: `plyr::summarise()` و `stats::filter()`. افكر في استخدام [**حزمة conflicted**](https://www.tidyverse.org/blog/2018/06/conflicted/).  

```
خطأ في install.packages: ERROR: فشل قفل الدليل 'C:\Users\Name\Documents\R\win-library\4.0' للتعديل
حاول إزالة 'C:\Users\Name\Documents\R\win-library\4.0/00LOCK'
```

إذا حصلت على خطأ يطلب منك إزالة ملف "00LOCK"، انتقل إلى مكتبة "R" في دليل الكمبيوتر الخاص بك (على سبيل المثال R/win-library/) وابحث عن مجلد يسمى "00LOCK". احذف هذا يدوياً، وحاول تثبيت الحزمة مرة أخرى. ربما تم إيقاف عملية التثبيت السابقة بشكل غير صحيح، مما أدى إلى ذلك.

### أخطاء الكائنات {.unnumbered}

```
لا يوجد ملف أو دليل:
```
إذا رأيت خطأ مثل هذا عند محاولة التصدير أو الاستيراد: تحقق من إملاء اسم الملف ومساره، وإذا كان المسار يحتوي على شرطات تأكد من أنها مائلة `/` وليس عكسية `\`. تأكد أيضاً من استخدام امتداد الملف الصحيح (على سبيل المثال .csv، .xlsx).

```
الكائن 'x' غير موجود
```
هذا يعني أن الكائن الذي تشير إليه لا يوجد. ربما لم يتم تشغيل الكود بشكل صحيح؟

```
خطأ في 'x': الفهرس خارج الحدود
```
هذا يعني أنك حاولت الوصول إلى شيء (عنصر من متجه أو قائمة) لم يكن موجوداً.

### أخطاء بناء الدوال {.unnumbered}

```
# تم تشغيل recode بدون إعادة تعريف المتغير x في mutate(x = recode(x, OLD = NEW)
خطأ: مشكلة في مدخل `mutate()` `hospital`.
المدخل .x مفقود، بدون قيمة افتراضية
المدخل `hospital` هو `recode(...)`.
```
هذا الخطأ أعلاه (`المدخل .x مفقود، بدون قيمة افتراضية`) شائع في `mutate()` إذا كنت تزوّد بدالة مثل `recode()` أو `replace_na()` حيث يتوقع منك توفير اسم العمود كالمدخل الأول. من السهل نسيان ذلك.

### أخطاء المنطق {.unnumbered}

```
خطأ في if
```
هذا يعني على الأرجح تم تطبيق بيان `if` على شيء لم يكن TRUE أو FALSE.

### أخطاء العوامل {.unnumbered}

```
# حاولت إضافة قيمة ("مفقود") إلى عامل (مع replace_na يعمل على عامل)
مشكلة في مدخل `mutate()` `age_cat`.
مستوى عامل غير صالح، تم إنشاء NA
المدخل `age_cat` هو `replace_na(age_cat, "مفقود")`. مستوى عامل غير صالح، تم إنشاء NA
```
إذا رأيت هذا الخطأ حول مستويات العوامل غير الصالحة، فمن المحتمل أن يكون لديك عمود من النوع Factor (الذي يحتوي على مستويات محددة مسبقًا) وحاولت إضافة قيمة جديدة إليه. قم بتحويله إلى نوع Character قبل إضافة قيمة جديدة.  

### رسم الأخطاء {.unnumbered}  

`خطأ: قيم غير كافية في مقياس يدوي. 3 مطلوبة ولكن تم توفير 2 فقط.`
ggplot() scale_fill_manual() values = c("orange", "purple") ... غير كافٍ لعدد مستويات العامل ... انظر ما إذا كانت NA الآن مستوى عامل...

```
لا يمكن إضافة كائن x
```
ربما لديك `+` إضافي في نهاية أمر ggplot يجب عليك حذفه.


### أخطاء R Markdown {.unnumbered}  

إذا كانت رسالة الخطأ تحتوي على شيء مثل `Error in options[[sprintf("fig.%s", i)]]`، تحقق من أن خيارات knitr في أعلى كل قطعة تستخدم بشكل صحيح `out.width = ` أو `out.height = ` و *ليس* `fig.width=` و `fig.height=`.

### متنوعات {.unnumbered}  

انظر ما إذا قمت بإعادة ترتيب أفعال **dplyr** المنقولة بالأنابيب ولم تقم بتبديل الأنبوب في الوسط، أو لم تقم بإزالة الأنبوب من النهاية بعد إعادة الترتيب.



<!-- ======================================================= -->
## الموارد { }

هذه مقالة أخرى تقوم بسرد [أخطاء برمجة R الشائعة التي يواجهها المبتدئون](https://www.r-bloggers.com/2016/06/common-r-programming-errors-faced-by-beginners/)
