# Häufige Fehler

Auf dieser Seite findest du eine Liste mit häufigen Fehlern und Lösungsvorschlägen für ihre Behebung.

## Fehlermeldungen interpretieren

R-Fehlermeldungen können manchmal kryptisch sein, also ist Google dein Freund. Suche die Fehlermeldung mit "R" und suche nach aktuellen Beiträgen in [StackExchange.com](StackExchange.com), [stackoverflow.com](stackoverflow.com), [community.rstudio.com](community.rstudio.com), Twitter (#rstats) und andere Foren, die von Programmierern genutzt werden, um Fragen und Antworten abzulegen. Versuche, aktuelle Beiträge zu finden, die ähnliche Probleme gelöst haben.

Wenn du nach langem Suchen keine Antwort auf dein Problem findest, kannst du eine *reproduzierbares Beispiel*("reprex") und stellst die Frage selbst. Siehe die Seite über [Hilfe erhalten] findest du Tipps, wie du ein reproduzierbares Beispiel erstellst und in Foren postest.

## Häufige Fehler

Im Folgenden listen wir einige häufige Fehler und mögliche Erklärungen/Lösungen auf. Einige davon stammen von Noam Ross, der die häufigsten Forenbeiträge auf Stack Overflow zu R-Fehlermeldungen analysiert hat (siehe Analyse [hier](https://github.com/noamross/zero-dependency-problems/blob/master/misc/stack-overflow-common-r-errors.md))

### Tippfehler {.unnumbered}

```
Error: unexpected symbol in:
"  geom_histogram(stat = "identity")+
  tidyquant::geom_ma(n=7, size = 2, color = "red" lty"
```

Wenn du "unerwartetes Symbol" siehst, überprüfe, ob Kommas fehlen

### Paketfehler {.unnumbered}

```
could not find function "x"...
```

Das bedeutet wahrscheinlich, dass du den Funktionsnamen falsch eingegeben hast oder vergessen hast, ein Paket zu installieren oder zu laden.

```
Error in select(data, var) : unused argument (var)
```

Du denkst, du verwendest `dplyr::select()` aber die `select()` Funktion wurde maskiert durch `MASS::select()` - angeben `dplyr::` oder ordne das Laden deines Pakets neu an, so dass dplyr nach allen anderen kommt.

Andere häufige Maskierungsfehler entstehen durch: `plyr::summarise()` und `stats::filter()`. Erwägen Sie die Verwendung der [**widersprüchlichen** Paket](https://www.tidyverse.org/blog/2018/06/conflicted/).

```
Error in install.packages : ERROR: failed to lock directory ‘C:\Users\Name\Documents\R\win-library\4.0' for modifying
Try removing ‘C:\Users\Name\Documents\R\win-library\4.0/00LOCK'
```

Wenn du eine Fehlermeldung erhältst, dass du eine "00LOCK"-Datei entfernen musst, gehe zu deiner "R"-Bibliothek in deinem Computerverzeichnis (z.B. R/win-library/) und suche nach einem Ordner namens "00LOCK". Lösche diesen manuell und versuche erneut, das Paket zu installieren. Wahrscheinlich wurde ein früherer Installationsvorgang unterbrochen, was zu diesem Problem geführt hat.

### Objektfehler {.unnumbered}

```
No such file or directory:
```

Wenn du eine solche Fehlermeldung siehst, wenn du versuchst zu exportieren oder zu importieren: Überprüfe die Schreibweise der Datei und des Dateipfads, und wenn der Pfad Schrägstriche enthält, stelle sicher, dass sie vorwärts gerichtet sind `/` und nicht rückwärts `\`. Vergewissere dich auch, dass du die richtige Dateierweiterung verwendet hast (z. B. .csv, .xlsx).

```
object 'x' not found 
```

Das bedeutet, dass ein Objekt, auf das du dich beziehst, nicht existiert. Vielleicht wurde der obige Code nicht richtig ausgeführt?

```
Error in 'x': subscript out of bounds
```

Das bedeutet, dass du versucht hast, auf etwas zuzugreifen (ein Element eines Vektors oder einer Liste), das nicht vorhanden ist.

### Funktionssyntax-Fehler {.unnumbered}

```
# ran recode without re-stating the x variable in mutate(x = recode(x, OLD = NEW)
Error: Problem with `mutate()` input `hospital`.
x argument ".x" is missing, with no default
i Input `hospital` is `recode(...)`.
```

Dieser Fehler oben (`argument .x is missing, with no default`) ist häufig in `mutate()` wenn du eine Funktion wie `recode()` oder `replace_na()` erwartet, dass du den Spaltennamen als erstes Argument angibst. Das ist leicht zu vergessen.

### Logische Fehler {.unnumbered}

```
Error in if
```

Das bedeutet wahrscheinlich eine `if` Anweisung auf etwas angewendet wurde, das nicht WAHR oder FALSCH war.

### Faktor-Fehler {.unnumbered}

```
#Tried to add a value ("Missing") to a factor (with replace_na operating on a factor)
Problem with `mutate()` input `age_cat`.
i invalid factor level, NA generated
i Input `age_cat` is `replace_na(age_cat, "Missing")`.invalid factor level, NA generated
```

Wenn du diese Fehlermeldung über ungültige Faktorstufen siehst, hast du wahrscheinlich eine Spalte der Klasse Faktor (die vordefinierte Stufen enthält) und versucht, ihr einen neuen Wert hinzuzufügen. Wandle sie in die Klasse Zeichen um, bevor du einen neuen Wert hinzufügst.

### Fehler beim Plotten {.unnumbered}

`Error: Insufficient values in manual scale. 3 needed but only 2 provided.`
ggplot() scale\_fill\_manual() values = c("orange", "purple") ... unzureichend für die Anzahl der Faktorstufen ... überlege, ob NA jetzt eine Faktorstufe ist...

```
Can't add x object
```

Du hast wahrscheinlich eine zusätzliche `+` am Ende eines ggplot-Befehls, das du löschen musst.

### R Markdown-Fehler {.unnumbered}

Wenn die Fehlermeldung etwas enthält wie `Error in options[[sprintf("fig.%s", i)]]` enthält, überprüfe, ob deine Knitr-Optionen am Anfang jedes Chunks die korrekte Verwendung der `out.width = ` oder `out.height = ` und *nicht* `fig.width=` und `fig.height=`.

### Sonstiges {.unnumbered}

Überlege dir, ob du die Rohrleitungen neu arrangiert hast **dplyr** Verben neu angeordnet hast und eine Pipe in der Mitte nicht ersetzt hast, oder ob du eine Pipe am Ende nicht entfernt hast, nachdem du sie neu angeordnet hast.

<!-- ======================================================= -->

## Ressourcen { }

Dies ist ein weiterer Blogbeitrag, der gängige [R Programmierfehler von Anfängern aufl](https://www.r-bloggers.com/2016/06/common-r-programming-errors-faced-by-beginners/)


