# Erros comuns  {#errors}

Esta página inclui uma lista de erros comuns e sugere soluções para solucioná-los.

## Interpretando mensagens de erro

Os erros no R podem ser enigmáticos às vezes, então use o Google como seu amigo. Pesquise a mensagem de erro com "R" e procure as postagens recentes em [StackExchange.com](StackExchange.com), [stackoverflow.com](stackoverflow.com), [community.rstudio.com](community.rstudio.com), twitter (#rstats) e outros fóruns de perguntas e respostas usados por programadores. Tente encontrar postagens recentes que resolveram problemas semelhantes.

Se você não conseguir encontrar uma resposta para o seu problema, mesmo depois de pesquisar muito, considere criar um *exemplo reprodutível* ("reprex", ou um MRE para *Minimal Reproducible Exemple* ) e postar a pergunta você mesmo. Consulte a página [Obtendo ajuda](#help) para dicas sobre como criar e postar um exemplo reprodutível em fóruns.

## Erros comuns  

Abaixo, listamos alguns erros comuns e potenciais explicações / soluções. Some of these are borrowed from Noam Ross who analyzed the most common forum posts on Stack Overflow about R error messages (see analysis [here](https://github.com/noamross/zero-dependency-problems/blob/master/misc/stack-overflow-common-r-errors.md))  


### Erros de digitação {.unnumbered}  

```
Error: unexpected symbol in:
"  geom_histogram(stat = "identity")+
  tidyquant::geom_ma(n=7, size = 2, color = "red" lty"
```
Se você vir um "unexpected symbol" (símbolo inesperado), verifique se há vírgulas faltando  

### Erros de pacote {.unnumbered}  

```
could not find function "x"...
```
Isso provavelmente significa que você digitou o nome da função incorretamente ou esqueceu de instalar / carregar um pacote.

```
Error in select(data, var) : unused argument (var)
```
Você acha que está usando `dplyr :: select ()` mas a função `select ()` foi mascarada por `MASS::select ()` - especifique `dplyr ::` ou reorganize o carregamento do pacote para que dplyr venha depois de todos os outros.

Outros erros comuns de mascaramento vêm de: `plyr::summarise()` and `stats::filter()`. Considere usar o pacote [**conflicted** package](https://www.tidyverse.org/blog/2018/06/conflicted/).

```
Error in install.packages : ERROR: failed to lock directory ‘C:\Users\Name\Documents\R\win-library\4.0’ for modifying
Try removing ‘C:\Users\Name\Documents\R\win-library\4.0/00LOCK’
```

Se você receber um erro dizendo que precisa remover um arquivo "00LOCK", vá para a biblioteca "R" no diretório do seu computador (por exemplo, R/win-library/) e procure uma pasta chamada "00LOCK". Exclua isso manualmente e tente instalar o pacote novamente. Provavelmente isso aconteceu porque um processo de instalação anterior foi interrompido.

### Erros de objeto {.unnumbered}  

```
No such file or directory:
```
Se você encontrar um erro como este na exportação ou importação: Verifique a ortografia do arquivo e do caminho do arquivo. Se o caminho contém barras, certifique-se de que estão para frente `/` e não para trás `\`. Certifique-se também de usar a extensão de arquivo correta (por exemplo, .csv, .xlsx).

```
object 'x' not found 
```
Isso significa que o objeto não existe. Talvez o código acima não tenha funcionado corretamente?

```
Error in 'x': subscript out of bounds
```
Isso significa que você tentou acessar algo (um elemento de um vetor ou uma lista) que não estava lá.

### Erros de sintaxe de função {.unnumbered}

```
# ran recode without re-stating the x variable in mutate(x = recode(x, OLD = NEW)
Error: Problem with `mutate()` input `hospital`.
x argument ".x" is missing, with no default
i Input `hospital` is `recode(...)`.
```
O erro acima (`argument ".x" is missing, with no default`) é comum em `mutate()` se você estiver fornecendo uma função como `recode ()` ou `replace_na()`, pois espera-se que você forneça a coluna nome como  primeiro argumento. Isso é fácil de esquecer.

### Erros lógicos {.unnumbered}  

```
Error in if
```

Isso provavelmente significa que uma instrução `if` foi aplicada a algo que não era VERDADEIRO ou FALSO.

### Erros de fator {.unnumbered}  

```
#Tried to add a value ("Missing") to a factor (with replace_na operating on a factor)
Problem with `mutate()` input `age_cat`.
i invalid factor level, NA generated
i Input `age_cat` is `replace_na(age_cat, "Missing")`.invalid factor level, NA generated
```
Se você encontrar este erro sobre níveis de fator inválidos, provavelmente tem uma coluna com uma variável do tipo fator (níveis predefinidos) e tentou adicionar um novo valor a ela. Converta-o para o tipo caracter antes de adicionar um novo valor.

### Erros de plotagem {.unnumbered}  

`Error: Insufficient values in manual scale. 3 needed but only 2 provided.`
ggplot() scale_fill_manual() values = c("orange", "purple") ... insufficient for number of factor levels ... consider whether NA is now a factor level...

```
Can't add x object
```
Provavelmente tem um `+` extra no final de um comando ggplot que você precisa excluir.

### Erros de R Markdown {.unnumbered}  

Se a mensagem de erro contiver algo como `Error in options[[sprintf("fig.%s", i)]]`, verifique se as opções do knitr no topo de cada bloco usam adequadamente `out.width = ` ou `out.height = ` e *não* `fig.width=` e `fig.height=`.

### Diversos {.unnumbered}  

Considere se você reorganizou os verbos **dplyr** e esqueceu de substituir um *pipe* (%>%) no meio do código ou se esqueceu um pipe na extremidade após reorganizar.

<!-- ======================================================= -->
## Recursos { }

Esta é outra postagem do blog que lista [erros de programação R enfrentados por iniciantes](https://www.r-bloggers.com/2016/06/common-r-programming-errors-faced-by-beginners/)
