
# Modeling {.tabset .tabset-fade}  


<!-- ======================================================= -->
## Overview {.tabset .tabset-fade .tabset-pills}

UNDER CONSTRUCTION



<!-- ======================================================= -->
## Preparation {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Preparation".  
Data preparation steps such as:  

* Loading dataset  
* Adding or changing variables  
* melting, pivoting, grouping, etc.   



<!-- ======================================================= -->
## Overview {.tabset .tabset-fade .tabset-pills}
Tidymodels

<!-- ======================================================= -->
## Logistic Regression {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## Multi-level modeling Regression {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## Survival analysis {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## Multi-stage Markov models {.tabset .tabset-fade .tabset-pills}

Liza Coyer TODO this? logitudinal data 


<!-- ======================================================= -->
## Tables of model results {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## Causal diagrams {.tabset .tabset-fade .tabset-pills}




