
# Моделирование {.tabset .tabset-fade}  


<!-- ======================================================= -->
## Обзор {.tabset .tabset-fade .tabset-pills}

В РАЗРАБОТКЕ



<!-- ======================================================= -->
## Подготовка {.tabset .tabset-fade .tabset-pills}

Сохранить название этого раздела как "Подготовка".  
Шаги подготовки данных, такие как:  

* Загрузка набора данных  
* Добавление или изменение переменных  
* Слияние, поворот, группировка и т.п.   



<!-- ======================================================= -->
## Обзор {.tabset .tabset-fade .tabset-pills}
Модели Tidymodels

<!-- ======================================================= -->
## Логистическая регрессия {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## Регрессия для многоуровневого моделирования {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## Анализ выживаемости {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## Многоэтапные модели Маркова {.tabset .tabset-fade .tabset-pills}

Liza Coyer СДЕЛАТЬ? продольные данные 


<!-- ======================================================= -->
## Таблицы с результатами модели {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## Диаграммы причинно-следственной связи {.tabset .tabset-fade .tabset-pills}




