---
title: "Outbreak Situation Report"
date: "4/24/2021"
output: pdf_document
---

```{r setup, echo=FALSE}
pacman::p_load(rio, here, tidyverse, janitor, incidence2, flextable)
linelist <- rio::import(here::here("data", "case_linelists", "linelist_cleaned.rds"))
set_flextable_defaults(fonts_ignore=TRUE)
```

This report is for the Incident Command team of the fictional outbreak of Ebola cases. **As of `r format(max(linelist$date_hospitalisation, na.rm=T), "%d %B")` there have been `r nrow(linelist)` cases reported as hospitalized.**  

## Summary table of cases by hospital 

```{r, echo=F, out.height="75%"}
linelist %>% 
  filter(!is.na(hospital)) %>% 
  group_by(hospital) %>% 
  summarise(cases = n(),
    deaths = sum(outcome == "Death", na.rm=T),
    recovered = sum(outcome == "Recover", na.rm=T)) %>% 
  adorn_totals() %>% 
  qflextable()
```

## Epidemic curve by age  

```{r, echo=F, warning=F, message=F, out.height = "50%", out.width="75%"}
# create epicurve
age_outbreak <- incidence(
  linelist,
  date_index = date_onset,   # date of onset for x-axis
  interval = "week",         # weekly aggregation of cases
  groups = age_cat)
     
# plot
plot(age_outbreak, n_breaks = 3, fill = age_cat, col_pal = muted, title = "Epidemic curve by age group")
```
