book:
  title: "The Epidemiologist R Handbook"
  search: 
    type: textbox
  repo-url: https://github.com/appliedepi/epihandbook_quarto
  # site-url: https://epirhandbook.com
  sharing: ["twitter", "facebook", "linkedin"]
  sidebar:
        logo: "images/Applied_Epi_logo.png"
        tools:
                - icon: twitter
                  href: "https://twitter.com/appliedepi"
                - icon: linkedin
                  href: "https://www.linkedin.com/company/appliedepi/"
                # - icon: github
                #   menu:
                #         - text: Source Code
                #           url: "https://github.com/appliedepi/epihandbook_quarto"
                #         - text: Report a Bug
                #           url: "https://github.com/appliedepi/epihandbook_quarto/issues/new"
  
  date: today
  date-format: "MMM D, YYYY"
  favicon: "images/Applied_Epi_logo.png"
  google-analytics: 
    tracking-id: "G-QXDW878QLX"
    anonymize-ip: true

  chapters:
  # INTRO & CONTRIBUTORS
  - index.qmd                              # objectives, how to read, authors, acknowledgements

  # ABOUT BOOK
  - part: "About this book"
    part-vn: "Về cuốn sách này"
    part-fr: "À propos de ce livre"
    part-es: "Acerca de este libro"
    part-jp: "本書について"
    part-tr: "Bu kitap hakkında"
    part-pt: "Sobre este livro"
    part-ru: "Об этой книге"
    part-de: "Über dieses Buch"
    chapters:
    - new_pages/editorial_style.qmd          # editorial style
    - new_pages/data_used.qmd                # data used
  
  # BASICS
  - part: "Basics"
    part-vn: "Nhập môn về R"
    part-fr: "Les bases de R"
    part-es: "Aspectos básicos"
    part-jp: "基本編"
    part-tr: "Temel Bilgiler"
    part-pt: "Básico"
    part-ru: "Основы"
    part-de: "Grundlagen"
    chapters:
    - new_pages/basics.qmd
    - new_pages/transition_to_R.qmd
    - new_pages/packages_suggested.qmd
    - new_pages/r_projects.qmd
    - new_pages/importing.qmd

  # DATA MANGEMENT
  - part: "Data Management"
    part-vn: "Quản lý dữ liệu"
    part-fr: "Gestion des données"
    part-es: "Gestión de datos"
    part-jp: "データマネジメント"
    part-tr: "Veri Yönetimi"
    part-pt: "Gerenciamento de Dados"
    part-ru: "Управление данными"
    part-de: "Datenmanagement"
    chapters:
    - new_pages/cleaning.qmd
    - new_pages/dates.qmd
    - new_pages/characters_strings.qmd
    - new_pages/factors.qmd
    - new_pages/pivoting.qmd
    - new_pages/grouping.qmd
    - new_pages/joining_matching.qmd
    - new_pages/deduplication.qmd
    - new_pages/iteration.qmd


  # ANALYSIS
  - part: "Analysis"
    part-vn: "Phân tích dữ liệu"
    part-fr: "Analyse"
    part-es: "Análisis"
    part-jp: "データ分析"
    part-tr: "Analiz"
    part-pt: "Análise dos Dados"
    part-ru: "Анализ"
    part-de: "Analyse"
    chapters:
    - new_pages/tables_descriptive.qmd
    - new_pages/stat_tests.qmd
    - new_pages/regression.qmd
    - new_pages/missing_data.qmd
    - new_pages/standardization.qmd
    - new_pages/moving_average.qmd
    - new_pages/time_series.qmd #done
    - new_pages/epidemic_models.qmd #done
    - new_pages/contact_tracing.qmd #done
    - new_pages/survey_analysis.qmd #done
    - new_pages/survival_analysis.qmd #done
    - new_pages/gis.qmd #done
  

  # DATA VIZ
  - part: "Data Visualization"
    part-vn: "Trực quan hóa dữ liệu"
    part-fr: "Visualisation des données"
    part-es: "Visualización de datos"
    part-jp: "データの可視化"
    part-tr: "Veri Görselleştirme"
    part-pt: "Visualização de Dados"
    part-ru: "Визуализация данных"
    part-de: "Datenvisualisierung"
    chapters:
    - new_pages/tables_presentation.qmd  #done
    - new_pages/ggplot_basics.qmd #done
    #new_pages/plot_continuous.qmd,
    #new_pages/plot_discrete.qmd,
    - new_pages/ggplot_tips.qmd #done
    - new_pages/epicurves.qmd #done
    - new_pages/age_pyramid.qmd #done
    - new_pages/heatmaps.qmd   #done
    - new_pages/diagrams.qmd  #done
    - new_pages/combination_analysis.qmd #done
    - new_pages/transmission_chains.qmd #done
    - new_pages/phylogenetic_trees.qmd #done
    - new_pages/interactive_plots.qmd #done

  # REPORTS AND DASHBOARDS
  - part: "Reports and dashboards"
    part-vn: "Báo cáo và dashboards"
    part-fr: "Rapports et tableaux de bord"
    part-es: "Informes y Dashboards"
    part-jp: "レポートとダッシュボード"
    part-tr: "Raporlar ve gösterge panoları"
    part-pt: "Relatórios e dashboards"
    part-ru: "Отчеты и информационные панели"
    part-de: "Berichte und Dashboards"
    chapters:
    - new_pages/rmarkdown.qmd #done
    - new_pages/reportfactory.qmd #done
    - new_pages/flexdashboard.qmd #done
    - new_pages/shiny_basics.qmd #done


  # MISCELLANEOUS
  - part: "Miscellaneous"
    part-vn: "Các chủ điểm khác"
    part-fr: "Autres sujets"
    part-es: "Miscelánea"
    part-jp: "その他"
    part-tr: "Çeşitli"
    part-pt: "Miscelânea"
    part-ru: "Разное"
    part-de: "Verschiedenes"
    chapters:
    - new_pages/writing_functions.qmd #done
    - new_pages/directories.qmd #done
    - new_pages/collaboration.qmd #done
    - new_pages/errors.qmd #done
    - new_pages/help.qmd #done
    #new_pages/relational_databases.qmd,
    - new_pages/network_drives.qmd #done
    - new_pages/data_table.qmd #done
    # new_pages/rstudio_advanced.qmd


