{
  "hash": "327da4b1f48651866b13f4bde19f978e",
  "result": {
    "markdown": "\n# Standardised rates { }  \n\nThis page will show you two ways to standardize an outcome, such as hospitalizations or mortality, by characteristics such as age and sex. \n\n* Using **dsr** package \n* Using **PHEindicatormethods** package  \n\nWe begin by extensively demonstrating the processes of data preparation/cleaning/joining, as this is common when combining population data from multiple countries, standard population data, deaths, etc.  \n\n## Overview  \n\nThere are two main ways to standardize: direct and indirect standardization.\nLet's say we would like to the standardize mortality rate by age and sex for country A and country B, and compare the standardized rates between these countries.\n\n* For direct standardization, you will have to know the number of the at-risk population and the number of deaths for each stratum of age and sex, for country A and country B. One stratum in our example could be females between ages 15-44.  \n* For indirect standardization, you only need to know the total number of deaths and the age- and sex structure of each country. This option is therefore feasible if age- and sex-specific mortality rates or population numbers are not available. Indirect standardization is furthermore preferable in case of small numbers per stratum, as estimates in direct standardization would be influenced by substantial sampling variation. \n\n<!-- ======================================================= -->\n## Preparation {  }\n\nTo show how standardization is done, we will use fictitious population counts and death counts from  country A and country B, by age (in 5 year categories) and sex (female, male). To make the datasets ready for use, we will perform the following preparation steps:  \n\n1. Load packages  \n2. Load datasets  \n3. Join the population and death data from the two countries\n4. Pivot longer so there is one row per age-sex stratum\n5. Clean the reference population (world standard population) and join it to the country data  \n\nIn your scenario, your data may come in a different format. Perhaps your data are by province, city, or other catchment area. You may have one row for each death and information on age and sex for each (or a significant proportion) of these deaths. In this case, see the pages on [Grouping data], [Pivoting data], and [Descriptive tables] to create a dataset with event and population counts per age-sex stratum.  \n\nWe also need a reference population, the standard population. For the purposes of this exercise we will use the `world_standard_population_by_sex`. The World standard population is based on the populations of 46 countries and was developed in 1960. There are many \"standard\" populations - as one example, the website of [NHS Scotland](https://www.opendata.nhs.scot/dataset/standard-populations) is quite informative on the European Standard Population, World Standard Population and Scotland Standard Population. \n\n<!-- ======================================================= -->\n### Load packages {.unnumbered}\n\nThis code chunk shows the loading of packages required for the analyses. In this handbook we emphasize `p_load()` from **pacman**, which installs the package if necessary *and* loads it for use. You can also load installed packages with  `library()` from **base** R. See the page on [R basics] for more information on R packages.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n     rio,                 # import/export data\n     here,                # locate files\n     stringr,             # cleaning characters and strings\n     frailtypack,         # needed for dsr, for frailty models\n     dsr,                 # standardise rates\n     PHEindicatormethods, # alternative for rate standardisation\n     tidyverse)           # data management and visualization\n```\n:::\n\n\n\n<span style=\"color: orange;\">**_CAUTION:_** If you have a newer version of R, the **dsr** package cannot be directly downloaded from CRAN. However, it is still available from the CRAN archive. You can install and use this one. </span>\n\nFor non-Mac users:  \n\n\n::: {.cell}\n\n```{.r .cell-code}\npackageurl <- \"https://cran.r-project.org/src/contrib/Archive/dsr/dsr_0.2.2.tar.gz\"\ninstall.packages(packageurl, repos=NULL, type=\"source\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Other solution that may work\nrequire(devtools)\ndevtools::install_version(\"dsr\", version=\"0.2.2\", repos=\"http:/cran.us.r.project.org\")\n```\n:::\n\n\nFor Mac users:  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequire(devtools)\ndevtools::install_version(\"dsr\", version=\"0.2.2\", repos=\"https://mac.R-project.org\")\n```\n:::\n\n\n\n\n\n### Load population data {.unnumbered}  \n\nSee the [Download handbook and data] page for instructions on how to download all the example data in the handbook. You can import the Standardisation page data directly into R from our Github repository by running the following `import()` commands:  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# import demographics for country A directly from Github\nA_demo <- import(\"https://github.com/appliedepi/epirhandbook_eng/raw/master/data/standardization/country_demographics.csv\")\n\n# import deaths for country A directly from Github\nA_deaths <- import(\"https://github.com/appliedepi/epirhandbook_eng/raw/master/data/standardization/deaths_countryA.csv\")\n\n# import demographics for country B directly from Github\nB_demo <- import(\"https://github.com/appliedepi/epirhandbook_eng/raw/master/data/standardization/country_demographics_2.csv\")\n\n# import deaths for country B directly from Github\nB_deaths <- import(\"https://github.com/appliedepi/epirhandbook_eng/raw/master/data/standardization/deaths_countryB.csv\")\n\n# import demographics for country B directly from Github\nstandard_pop_data <- import(\"https://github.com/appliedepi/epirhandbook_eng/raw/master/data/standardization/world_standard_population_by_sex.csv\")\n```\n:::\n\n\n\nFirst we load the demographic data (counts of males and females by 5-year age category) for the two countries that we will be comparing, \"Country A\" and \"Country B\".  \n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Country A\nA_demo <- import(\"country_demographics.csv\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-d13a76dc26ce4e09ade3\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d13a76dc26ce4e09ade3\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\"],[\"0-4\",\"5-9\",\"10-14\",\"15-19\",\"20-24\",\"25-29\",\"30-34\",\"35-39\",\"40-44\",\"45-49\",\"50-54\",\"55-59\",\"60-64\",\"65-69\",\"70-74\",\"75-79\",\"80-84\",\"85\"],[7828087,6705882,5601230,4576430,3734111,3111651,2571215,2121247,1735468,1418749,1145345,900239,685141,500248,347093,202240,94325,40402],[7674675,6592449,5522555,4533885,3726537,3118040,2592416,2150490,1771213,1459439,1193903,956070,745682,563894,416543,258538,130479,64656]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>Country<\\/th>\\n      <th>age_cat5<\\/th>\\n      <th>m<\\/th>\\n      <th>f<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,3]},{\"name\":\"Country\",\"targets\":0},{\"name\":\"age_cat5\",\"targets\":1},{\"name\":\"m\",\"targets\":2},{\"name\":\"f\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Country B\nB_demo <- import(\"country_demographics_2.csv\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-7e072c7207f1105c4fb2\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7e072c7207f1105c4fb2\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\"],[\"0-4\",\"5-9\",\"10-14\",\"15-19\",\"20-24\",\"25-29\",\"30-34\",\"35-39\",\"40-44\",\"45-49\",\"50-54\",\"55-59\",\"60-64\",\"65-69\",\"70-74\",\"75-79\",\"80-84\",\"85\"],[513458,508728,673522,844532,965423,1243552,1400065,1428773,1546221,1562880,2355220,2324555,2988200,2527110,1552200,1466902,876251,1073611],[503262,559249,652455,145453,965237,1238640,1392676,1505040,1671213,1459439,2218733,3528103,3204770,2500130,1683925,1683828,987362,1147563]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>Country<\\/th>\\n      <th>age_cat5<\\/th>\\n      <th>m<\\/th>\\n      <th>f<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,3]},{\"name\":\"Country\",\"targets\":0},{\"name\":\"age_cat5\",\"targets\":1},{\"name\":\"m\",\"targets\":2},{\"name\":\"f\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\n\n\n\n### Load death counts {.unnumbered}  \n\nConveniently, we also have the counts of deaths during the time period of interest, by age and sex. Each country's counts are in a separate file, shown below.   \n\n\n::: {.cell}\n\n:::\n\n\nDeaths in Country A\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-a8877eb23caec5e75fc3\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a8877eb23caec5e75fc3\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\"],[\"0-4\",\"5-9\",\"10-14\",\"15-19\",\"20-24\",\"25-29\",\"30-34\",\"35-39\",\"40-44\",\"45-49\",\"50-54\",\"55-59\",\"60-64\",\"65-69\",\"70-74\",\"75-79\",\"80-84\",\"85\"],[224,257,251,245,334,245,154,189,334,342,565,432,543,432,245,543,234,354],[194,254,232,214,316,224,163,167,354,354,463,574,493,295,175,380,177,392]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>Country<\\/th>\\n      <th>AgeCat<\\/th>\\n      <th>Male<\\/th>\\n      <th>Female<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,3]},{\"name\":\"Country\",\"targets\":0},{\"name\":\"AgeCat\",\"targets\":1},{\"name\":\"Male\",\"targets\":2},{\"name\":\"Female\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nDeaths in Country B\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-62693d36cba518665cf2\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-62693d36cba518665cf2\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\"],[\"0-4\",\"5-9\",\"10-14\",\"15-19\",\"20-24\",\"25-29\",\"30-34\",\"35-39\",\"40-44\",\"45-49\",\"50-54\",\"55-59\",\"60-64\",\"65-69\",\"70-74\",\"75-79\",\"80-84\",\"85\"],[34,37,51,145,434,120,100,143,307,354,463,639,706,232,275,543,234,274],[54,24,32,154,276,254,123,164,254,354,453,654,435,354,165,432,287,395]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>Country<\\/th>\\n      <th>AgeCat<\\/th>\\n      <th>Male<\\/th>\\n      <th>Female<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,3]},{\"name\":\"Country\",\"targets\":0},{\"name\":\"AgeCat\",\"targets\":1},{\"name\":\"Male\",\"targets\":2},{\"name\":\"Female\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n### Clean populations and deaths {.unnumbered}  \n\n\nWe need to join and transform these data in the following ways:  \n\n* Combine country populations into one dataset and pivot \"long\" so that each age-sex stratum is one row  \n* Combine country death counts into one dataset and pivot \"long\" so each age-sex stratum is one row  \n* Join the deaths to the populations  \n\nFirst, we combine the country populations datasets, pivot longer, and do minor cleaning. See the page on [Pivoting data] for more detail.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\npop_countries <- A_demo %>%  # begin with country A dataset\n     bind_rows(B_demo) %>%        # bind rows, because cols are identically named\n     pivot_longer(                       # pivot longer\n          cols = c(m, f),                   # columns to combine into one\n          names_to = \"Sex\",                 # name for new column containing the category (\"m\" or \"f\") \n          values_to = \"Population\") %>%     # name for new column containing the numeric values pivoted\n     mutate(Sex = recode(Sex,            # re-code values for clarity\n          \"m\" = \"Male\",\n          \"f\" = \"Female\"))\n```\n:::\n\n\nThe combined population data now look like this (click through to see countries A and B):  \n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-c51fbd6eed509a5eecf8\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c51fbd6eed509a5eecf8\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\"],[\"0-4\",\"0-4\",\"5-9\",\"5-9\",\"10-14\",\"10-14\",\"15-19\",\"15-19\",\"20-24\",\"20-24\",\"25-29\",\"25-29\",\"30-34\",\"30-34\",\"35-39\",\"35-39\",\"40-44\",\"40-44\",\"45-49\",\"45-49\",\"50-54\",\"50-54\",\"55-59\",\"55-59\",\"60-64\",\"60-64\",\"65-69\",\"65-69\",\"70-74\",\"70-74\",\"75-79\",\"75-79\",\"80-84\",\"80-84\",\"85\",\"85\",\"0-4\",\"0-4\",\"5-9\",\"5-9\",\"10-14\",\"10-14\",\"15-19\",\"15-19\",\"20-24\",\"20-24\",\"25-29\",\"25-29\",\"30-34\",\"30-34\",\"35-39\",\"35-39\",\"40-44\",\"40-44\",\"45-49\",\"45-49\",\"50-54\",\"50-54\",\"55-59\",\"55-59\",\"60-64\",\"60-64\",\"65-69\",\"65-69\",\"70-74\",\"70-74\",\"75-79\",\"75-79\",\"80-84\",\"80-84\",\"85\",\"85\"],[\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\"],[7828087,7674675,6705882,6592449,5601230,5522555,4576430,4533885,3734111,3726537,3111651,3118040,2571215,2592416,2121247,2150490,1735468,1771213,1418749,1459439,1145345,1193903,900239,956070,685141,745682,500248,563894,347093,416543,202240,258538,94325,130479,40402,64656,513458,503262,508728,559249,673522,652455,844532,145453,965423,965237,1243552,1238640,1400065,1392676,1428773,1505040,1546221,1671213,1562880,1459439,2355220,2218733,2324555,3528103,2988200,3204770,2527110,2500130,1552200,1683925,1466902,1683828,876251,987362,1073611,1147563]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>Country<\\/th>\\n      <th>age_cat5<\\/th>\\n      <th>Sex<\\/th>\\n      <th>Population<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":3},{\"name\":\"Country\",\"targets\":0},{\"name\":\"age_cat5\",\"targets\":1},{\"name\":\"Sex\",\"targets\":2},{\"name\":\"Population\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nAnd now we perform similar operations on the two deaths datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths_countries <- A_deaths %>%    # begin with country A deaths dataset\n     bind_rows(B_deaths) %>%        # bind rows with B dataset, because cols are identically named\n     pivot_longer(                  # pivot longer\n          cols = c(Male, Female),        # column to transform into one\n          names_to = \"Sex\",              # name for new column containing the category (\"m\" or \"f\") \n          values_to = \"Deaths\") %>%      # name for new column containing the numeric values pivoted\n     rename(age_cat5 = AgeCat)      # rename for clarity\n```\n:::\n\n\nThe deaths data now look like this, and contain data from both countries: \n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-cd2517f232b6fc3811c7\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-cd2517f232b6fc3811c7\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\"],[\"0-4\",\"0-4\",\"5-9\",\"5-9\",\"10-14\",\"10-14\",\"15-19\",\"15-19\",\"20-24\",\"20-24\",\"25-29\",\"25-29\",\"30-34\",\"30-34\",\"35-39\",\"35-39\",\"40-44\",\"40-44\",\"45-49\",\"45-49\",\"50-54\",\"50-54\",\"55-59\",\"55-59\",\"60-64\",\"60-64\",\"65-69\",\"65-69\",\"70-74\",\"70-74\",\"75-79\",\"75-79\",\"80-84\",\"80-84\",\"85\",\"85\",\"0-4\",\"0-4\",\"5-9\",\"5-9\",\"10-14\",\"10-14\",\"15-19\",\"15-19\",\"20-24\",\"20-24\",\"25-29\",\"25-29\",\"30-34\",\"30-34\",\"35-39\",\"35-39\",\"40-44\",\"40-44\",\"45-49\",\"45-49\",\"50-54\",\"50-54\",\"55-59\",\"55-59\",\"60-64\",\"60-64\",\"65-69\",\"65-69\",\"70-74\",\"70-74\",\"75-79\",\"75-79\",\"80-84\",\"80-84\",\"85\",\"85\"],[\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\"],[224,194,257,254,251,232,245,214,334,316,245,224,154,163,189,167,334,354,342,354,565,463,432,574,543,493,432,295,245,175,543,380,234,177,354,392,34,54,37,24,51,32,145,154,434,276,120,254,100,123,143,164,307,254,354,354,463,453,639,654,706,435,232,354,275,165,543,432,234,287,274,395]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>Country<\\/th>\\n      <th>age_cat5<\\/th>\\n      <th>Sex<\\/th>\\n      <th>Deaths<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":3},{\"name\":\"Country\",\"targets\":0},{\"name\":\"age_cat5\",\"targets\":1},{\"name\":\"Sex\",\"targets\":2},{\"name\":\"Deaths\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\nWe now join the deaths and population data based on common columns `Country`, `age_cat5`, and `Sex`. This adds the column `Deaths`.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_data <- pop_countries %>% \n     left_join(deaths_countries, by = c(\"Country\", \"age_cat5\", \"Sex\"))\n```\n:::\n\n\nWe can now classify `Sex`, `age_cat5`, and `Country` as factors and set the level order using `fct_relevel()` function from the **forcats** package, as described in the page on [Factors]. Note, classifying the factor levels doesn't visibly change the data, but the `arrange()` command does sort it by Country, age category, and sex.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_data <- country_data %>% \n  mutate(\n    Country = fct_relevel(Country, \"A\", \"B\"),\n      \n    Sex = fct_relevel(Sex, \"Male\", \"Female\"),\n        \n    age_cat5 = fct_relevel(\n      age_cat5,\n      \"0-4\", \"5-9\", \"10-14\", \"15-19\",\n      \"20-24\", \"25-29\",  \"30-34\", \"35-39\",\n      \"40-44\", \"45-49\", \"50-54\", \"55-59\",\n      \"60-64\", \"65-69\", \"70-74\",\n      \"75-79\", \"80-84\", \"85\")) %>% \n          \n  arrange(Country, age_cat5, Sex)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-5c702e366ed312b4202e\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5c702e366ed312b4202e\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\"],[\"0-4\",\"0-4\",\"5-9\",\"5-9\",\"10-14\",\"10-14\",\"15-19\",\"15-19\",\"20-24\",\"20-24\",\"25-29\",\"25-29\",\"30-34\",\"30-34\",\"35-39\",\"35-39\",\"40-44\",\"40-44\",\"45-49\",\"45-49\",\"50-54\",\"50-54\",\"55-59\",\"55-59\",\"60-64\",\"60-64\",\"65-69\",\"65-69\",\"70-74\",\"70-74\",\"75-79\",\"75-79\",\"80-84\",\"80-84\",\"85\",\"85\",\"0-4\",\"0-4\",\"5-9\",\"5-9\",\"10-14\",\"10-14\",\"15-19\",\"15-19\",\"20-24\",\"20-24\",\"25-29\",\"25-29\",\"30-34\",\"30-34\",\"35-39\",\"35-39\",\"40-44\",\"40-44\",\"45-49\",\"45-49\",\"50-54\",\"50-54\",\"55-59\",\"55-59\",\"60-64\",\"60-64\",\"65-69\",\"65-69\",\"70-74\",\"70-74\",\"75-79\",\"75-79\",\"80-84\",\"80-84\",\"85\",\"85\"],[\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\"],[7828087,7674675,6705882,6592449,5601230,5522555,4576430,4533885,3734111,3726537,3111651,3118040,2571215,2592416,2121247,2150490,1735468,1771213,1418749,1459439,1145345,1193903,900239,956070,685141,745682,500248,563894,347093,416543,202240,258538,94325,130479,40402,64656,513458,503262,508728,559249,673522,652455,844532,145453,965423,965237,1243552,1238640,1400065,1392676,1428773,1505040,1546221,1671213,1562880,1459439,2355220,2218733,2324555,3528103,2988200,3204770,2527110,2500130,1552200,1683925,1466902,1683828,876251,987362,1073611,1147563],[224,194,257,254,251,232,245,214,334,316,245,224,154,163,189,167,334,354,342,354,565,463,432,574,543,493,432,295,245,175,543,380,234,177,354,392,34,54,37,24,51,32,145,154,434,276,120,254,100,123,143,164,307,254,354,354,463,453,639,654,706,435,232,354,275,165,543,432,234,287,274,395]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>Country<\\/th>\\n      <th>age_cat5<\\/th>\\n      <th>Sex<\\/th>\\n      <th>Population<\\/th>\\n      <th>Deaths<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[3,4]},{\"name\":\"Country\",\"targets\":0},{\"name\":\"age_cat5\",\"targets\":1},{\"name\":\"Sex\",\"targets\":2},{\"name\":\"Population\",\"targets\":3},{\"name\":\"Deaths\",\"targets\":4}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n<span style=\"color: orange;\">**_CAUTION:_** If you have few deaths per stratum, consider using 10-, or 15-year categories, instead of 5-year categories for age.</span>\n\n\n\n\n### Load reference population {.unnumbered}  \n\nLastly, for the direct standardisation, we import the reference population (world \"standard population\" by sex)\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reference population\nstandard_pop_data <- import(\"world_standard_population_by_sex.csv\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-ec5c210fc12c095be77c\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ec5c210fc12c095be77c\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"0-4 years\",\"0-4 years\",\"5-9 years\",\"5-9 years\",\"10-14 years\",\"10-14 years\",\"15-19 years\",\"15-19 years\",\"20-24 years\",\"20-24 years\",\"25-29 years\",\"25-29 years\",\"30-34 years\",\"30-34 years\",\"35-39 years\",\"35-39 years\",\"40-44 years\",\"40-44 years\",\"45-49 years\",\"45-49 years\",\"50-54 years\",\"50-54 years\",\"55-59 years\",\"55-59 years\",\"60-64 years\",\"60-64 years\",\"65-69 years\",\"65-69 years\",\"70-74 years\",\"70-74 years\",\"75-79 years\",\"75-79 years\",\"80-84 years\",\"80-84 years\",\"85plus years\",\"85plus years\"],[\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\"],[12000,12000,10000,10000,9000,9000,9000,9000,8000,8000,8000,8000,6000,6000,6000,6000,6000,6000,6000,6000,5000,5000,4000,4000,4000,4000,3000,3000,2000,2000,1000,1000,500,500,500,500]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>age_cat5<\\/th>\\n      <th>Sex<\\/th>\\n      <th>WorldStandardPopulation<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":2},{\"name\":\"age_cat5\",\"targets\":0},{\"name\":\"Sex\",\"targets\":1},{\"name\":\"WorldStandardPopulation\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\n\n<!-- ======================================================= -->\n### Clean reference population {.unnumbered}\n\nThe age category values in the `country_data` and `standard_pop_data` data frames will need to be aligned.  \n\nCurrently, the values of the column `age_cat5` from the `standard_pop_data` data frame contain the word \"years\" and \"plus\", while those of the `country_data` data frame do not. We will have to make the age category values match. We use `str_replace_all()` from the **stringr** package, as described in the page on [Characters and strings], to replace these patterns with no space `\"\"`.  \n\nFurthermore, the package **dsr** expects that in the standard population, the column containing counts will be called `\"pop\"`. So we rename that column accordingly.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove specific string from column values\nstandard_pop_clean <- standard_pop_data %>%\n     mutate(\n          age_cat5 = str_replace_all(age_cat5, \"years\", \"\"),   # remove \"year\"\n          age_cat5 = str_replace_all(age_cat5, \"plus\", \"\"),    # remove \"plus\"\n          age_cat5 = str_replace_all(age_cat5, \" \", \"\")) %>%   # remove \" \" space\n     \n     rename(pop = WorldStandardPopulation)   # change col name to \"pop\", as this is expected by dsr package\n```\n:::\n\n\n<span style=\"color: orange;\">**_CAUTION:_** If you try to use `str_replace_all()` to remove a plus *symbol*, it won't work because it is a special symbol. \"Escape\" the specialnes by putting two back slashes in front, as in `str_replace_call(column, \"\\\\+\", \"\")`. </span>\n\n### Create dataset with standard population {#standard_all .unnumbered}  \n\nFinally, the package **PHEindicatormethods**, detailed [below](#standard_phe), expects the standard populations joined to the country event and population counts. So, we will create a dataset `all_data` for that purpose.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_data <- left_join(country_data, standard_pop_clean, by=c(\"age_cat5\", \"Sex\"))\n```\n:::\n\n\nThis complete dataset looks like this:  \n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-0ec4f23961de240cd9a2\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-0ec4f23961de240cd9a2\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\"],[\"0-4\",\"0-4\",\"5-9\",\"5-9\",\"10-14\",\"10-14\",\"15-19\",\"15-19\",\"20-24\",\"20-24\",\"25-29\",\"25-29\",\"30-34\",\"30-34\",\"35-39\",\"35-39\",\"40-44\",\"40-44\",\"45-49\",\"45-49\",\"50-54\",\"50-54\",\"55-59\",\"55-59\",\"60-64\",\"60-64\",\"65-69\",\"65-69\",\"70-74\",\"70-74\",\"75-79\",\"75-79\",\"80-84\",\"80-84\",\"85\",\"85\",\"0-4\",\"0-4\",\"5-9\",\"5-9\",\"10-14\",\"10-14\",\"15-19\",\"15-19\",\"20-24\",\"20-24\",\"25-29\",\"25-29\",\"30-34\",\"30-34\",\"35-39\",\"35-39\",\"40-44\",\"40-44\",\"45-49\",\"45-49\",\"50-54\",\"50-54\",\"55-59\",\"55-59\",\"60-64\",\"60-64\",\"65-69\",\"65-69\",\"70-74\",\"70-74\",\"75-79\",\"75-79\",\"80-84\",\"80-84\",\"85\",\"85\"],[\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\"],[7828087,7674675,6705882,6592449,5601230,5522555,4576430,4533885,3734111,3726537,3111651,3118040,2571215,2592416,2121247,2150490,1735468,1771213,1418749,1459439,1145345,1193903,900239,956070,685141,745682,500248,563894,347093,416543,202240,258538,94325,130479,40402,64656,513458,503262,508728,559249,673522,652455,844532,145453,965423,965237,1243552,1238640,1400065,1392676,1428773,1505040,1546221,1671213,1562880,1459439,2355220,2218733,2324555,3528103,2988200,3204770,2527110,2500130,1552200,1683925,1466902,1683828,876251,987362,1073611,1147563],[224,194,257,254,251,232,245,214,334,316,245,224,154,163,189,167,334,354,342,354,565,463,432,574,543,493,432,295,245,175,543,380,234,177,354,392,34,54,37,24,51,32,145,154,434,276,120,254,100,123,143,164,307,254,354,354,463,453,639,654,706,435,232,354,275,165,543,432,234,287,274,395],[12000,12000,10000,10000,9000,9000,9000,9000,8000,8000,8000,8000,6000,6000,6000,6000,6000,6000,6000,6000,5000,5000,4000,4000,4000,4000,3000,3000,2000,2000,1000,1000,500,500,500,500,12000,12000,10000,10000,9000,9000,9000,9000,8000,8000,8000,8000,6000,6000,6000,6000,6000,6000,6000,6000,5000,5000,4000,4000,4000,4000,3000,3000,2000,2000,1000,1000,500,500,500,500]],\"container\":\"<table class=\\\"white-space: nowrap\\\">\\n  <thead>\\n    <tr>\\n      <th>Country<\\/th>\\n      <th>age_cat5<\\/th>\\n      <th>Sex<\\/th>\\n      <th>Population<\\/th>\\n      <th>Deaths<\\/th>\\n      <th>pop<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":5,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[3,4,5]},{\"name\":\"Country\",\"targets\":0},{\"name\":\"age_cat5\",\"targets\":1},{\"name\":\"Sex\",\"targets\":2},{\"name\":\"Population\",\"targets\":3},{\"name\":\"Deaths\",\"targets\":4},{\"name\":\"pop\",\"targets\":5}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\n\n<!-- ======================================================= -->\n## **dsr** package {  }\n \nBelow we demonstrate calculating and comparing directly standardized rates using the **dsr** package. The **dsr** package allows you to calculate and compare directly standardized rates (no indirectly standardized rates!).\n  \nIn the data Preparation section, we made separate datasets for country counts and standard population:  \n\n1) the `country_data` object, which is a population table with the number of population and number of deaths per stratum per country  \n2) the `standard_pop_clean` object, containing the number of population per stratum for our reference population, the World Standard Population  \n\nWe will use these separate datasets for the **dsr** approach.  \n\n\n<!-- ======================================================= -->\n### Standardized rates {.unnumbered}\n\nBelow, we calculate rates per country directly standardized for age and sex. We use the `dsr()` function. \n\nOf note - `dsr()` expects one data frame for the country populations and event counts (deaths), *and a **separate** data frame with the reference population*. It also expects that in this reference population dataset the unit-time column name is \"pop\" (we assured this in the data Preparation section).  \n\nThere are many arguments, as annotated in the code below. Notably, `event = ` is set to the column `Deaths`, and the `fu = ` (\"follow-up\") is set to the `Population` column. We set the subgroups of comparison as the column `Country` and we standardize based on `age_cat5` and `Sex`. These last two columns are not assigned a particular named argument. See `?dsr` for details. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate rates per country directly standardized for age and sex\nmortality_rate <- dsr::dsr(\n     data = country_data,  # specify object containing number of deaths per stratum\n     event = Deaths,       # column containing number of deaths per stratum \n     fu = Population,      # column containing number of population per stratum\n     subgroup = Country,   # units we would like to compare\n     age_cat5,             # other columns - rates will be standardized by these\n     Sex,\n     refdata = standard_pop_clean, # reference population data frame, with column called pop\n     method = \"gamma\",      # method to calculate 95% CI\n     sig = 0.95,            # significance level\n     mp = 100000,           # we want rates per 100.000 population\n     decimals = 2)          # number of decimals)\n\n\n# Print output as nice-looking HTML table\nknitr::kable(mortality_rate) # show mortality rate before and after direct standardization\n```\n\n::: {.cell-output-display}\n|Subgroup | Numerator| Denominator| Crude Rate (per 1e+05)| 95% LCL (Crude)| 95% UCL (Crude)| Std Rate (per 1e+05)| 95% LCL (Std)| 95% UCL (Std)|\n|:--------|---------:|-----------:|----------------------:|---------------:|---------------:|--------------------:|-------------:|-------------:|\n|A        |     11344|    86790567|                  13.07|           12.83|           13.31|                23.57|         23.08|         24.06|\n|B        |      9955|    52898281|                  18.82|           18.45|           19.19|                19.33|         18.46|         20.22|\n:::\n:::\n\n\nAbove, we see that while country A had a lower crude mortality rate than country B, it has a higher standardized rate after direct age and sex standardization.\n\n\n\n\n<!-- ======================================================= -->\n### Standardized rate ratios {.unnumbered}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate RR\nmortality_rr <- dsr::dsrr(\n     data = country_data, # specify object containing number of deaths per stratum\n     event = Deaths,      # column containing number of deaths per stratum \n     fu = Population,     # column containing number of population per stratum\n     subgroup = Country,  # units we would like to compare\n     age_cat5,\n     Sex,                 # characteristics to which we would like to standardize \n     refdata = standard_pop_clean, # reference population, with numbers in column called pop\n     refgroup = \"B\",      # reference for comparison\n     estimate = \"ratio\",  # type of estimate\n     sig = 0.95,          # significance level\n     mp = 100000,         # we want rates per 100.000 population\n     decimals = 2)        # number of decimals\n\n# Print table\nknitr::kable(mortality_rr) \n```\n\n::: {.cell-output-display}\n|Comparator |Reference | Std Rate (per 1e+05)| Rate Ratio (RR)| 95% LCL (RR)| 95% UCL (RR)|\n|:----------|:---------|--------------------:|---------------:|------------:|------------:|\n|A          |B         |                23.57|            1.22|         1.17|         1.27|\n|B          |B         |                19.33|            1.00|         0.94|         1.06|\n:::\n:::\n\n\nThe standardized mortality rate is 1.22 times higher in country A compared to country B (95% CI 1.17-1.27).\n\n<!-- ======================================================= -->\n### Standardized rate difference {.unnumbered}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate RD\nmortality_rd <- dsr::dsrr(\n     data = country_data,       # specify object containing number of deaths per stratum\n     event = Deaths,            # column containing number of deaths per stratum \n     fu = Population,           # column containing number of population per stratum\n     subgroup = Country,        # units we would like to compare\n     age_cat5,                  # characteristics to which we would like to standardize\n     Sex,                        \n     refdata = standard_pop_clean, # reference population, with numbers in column called pop\n     refgroup = \"B\",            # reference for comparison\n     estimate = \"difference\",   # type of estimate\n     sig = 0.95,                # significance level\n     mp = 100000,               # we want rates per 100.000 population\n     decimals = 2)              # number of decimals\n\n# Print table\nknitr::kable(mortality_rd) \n```\n\n::: {.cell-output-display}\n|Comparator |Reference | Std Rate (per 1e+05)| Rate Difference (RD)| 95% LCL (RD)| 95% UCL (RD)|\n|:----------|:---------|--------------------:|--------------------:|------------:|------------:|\n|A          |B         |                23.57|                 4.24|         3.24|         5.24|\n|B          |B         |                19.33|                 0.00|        -1.24|         1.24|\n:::\n:::\n\n\nCountry A has 4.24 additional deaths per 100.000 population (95% CI 3.24-5.24) compared to country A.\n\n\n\n\n\n\n\n<!-- ======================================================= -->\n## **PHEindicatormethods** package {#standard_phe  }\n\nAnother way of calculating standardized rates is with the **PHEindicatormethods** package. This package allows you to calculate directly as well as indirectly standardized rates. We will show both.  \n\nThis section will use the `all_data` data frame created at the end of the Preparation section. This data frame includes the country populations, death events, and the world standard reference population. You can view it [here](#standard_all).  \n\n\n\n<!-- ======================================================= -->\n### Directly standardized rates {.unnumbered}\n\nBelow, we first group the data by Country and then pass it to the function `phe_dsr()` to get directly standardized rates per country.\n\nOf note - the reference (standard) population can be provided as a **column within the country-specific data frame** or as a **separate vector**. If provided within the country-specific data frame, you have to set `stdpoptype = \"field\"`. If provided as a vector, set `stdpoptype = \"vector\"`. In the latter case, you have to make sure the ordering of rows by strata is similar in both the country-specific data frame and the reference population, as records will be matched by position. In our example below, we provided the reference population as a column within the country-specific data frame.\n\nSee the help with `?phr_dsr` or the links in the References section for more information.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate rates per country directly standardized for age and sex\nmortality_ds_rate_phe <- all_data %>%\n     group_by(Country) %>%\n     PHEindicatormethods::phe_dsr(\n          x = Deaths,                 # column with observed number of events\n          n = Population,             # column with non-standard pops for each stratum\n          stdpop = pop,               # standard populations for each stratum\n          stdpoptype = \"field\")       # either \"vector\" for a standalone vector or \"field\" meaning std populations are in the data  \n\n# Print table\nknitr::kable(mortality_ds_rate_phe)\n```\n\n::: {.cell-output-display}\n|Country | total_count| total_pop|    value|  lowercl|  uppercl|confidence |statistic      |method |\n|:-------|-----------:|---------:|--------:|--------:|--------:|:----------|:--------------|:------|\n|A       |       11344|  86790567| 23.56686| 23.08107| 24.05944|95%        |dsr per 100000 |Dobson |\n|B       |        9955|  52898281| 19.32549| 18.45516| 20.20882|95%        |dsr per 100000 |Dobson |\n:::\n:::\n\n\n<!-- ======================================================= -->\n### Indirectly standardized rates {#standard_indirect .unnumbered}\n\nFor indirect standardization, you need a reference population with the number of deaths and number of population per stratum. In this example, we will be calculating rates for country A *using country B as the reference population*, as the `standard_pop_clean` reference population does not include number of deaths per stratum. \n\nBelow, we first create the reference population from country B. Then, we pass mortality and population data for country A, combine it with the reference population, and pass it to the function `calculate_ISRate()`, to get indirectly standardized rates. Of course, you can do it also vice versa.\n\nOf note - in our example below, the reference population is provided as a separate data frame. In this case, we make sure that `x = `, `n = `, `x_ref = ` and `n_ref = ` vectors are all ordered by the same standardization category (stratum) values as that in our country-specific data frame, as records will be matched by position.\n\nSee the help with `?phr_isr` or the links in the References section for more information.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create reference population\nrefpopCountryB <- country_data %>% \n  filter(Country == \"B\") \n\n# Calculate rates for country A indirectly standardized by age and sex\nmortality_is_rate_phe_A <- country_data %>%\n     filter(Country == \"A\") %>%\n     PHEindicatormethods::calculate_ISRate(\n          x = Deaths,                 # column with observed number of events\n          n = Population,             # column with non-standard pops for each stratum\n          x_ref = refpopCountryB$Deaths,  # reference number of deaths for each stratum\n          n_ref = refpopCountryB$Population)  # reference population for each stratum\n\n# Print table\nknitr::kable(mortality_is_rate_phe_A)\n```\n\n::: {.cell-output-display}\n| observed| expected| ref_rate|    value|  lowercl|  uppercl|confidence |statistic                               |method |\n|--------:|--------:|--------:|--------:|--------:|--------:|:----------|:---------------------------------------|:------|\n|    11344| 15847.42| 18.81914| 13.47123| 13.22446| 13.72145|95%        |indirectly standardised rate per 100000 |Byars  |\n:::\n:::\n\n\n<!-- ======================================================= -->\n## Resources {  }\n\nIf you would like to see another reproducible example using **dsr** please see [this vignette]( https://mran.microsoft.com/snapshot/2020-02-12/web/packages/dsr/vignettes/dsr.html)  \n\nFor another example using **PHEindicatormethods**, please go to [this website](https://mran.microsoft.com/snapshot/2018-10-22/web/packages/PHEindicatormethods/vignettes/IntroductiontoPHEindicatormethods.html)  \n\nSee the **PHEindicatormethods** [reference pdf file](https://cran.r-project.org/web/packages/PHEindicatormethods/PHEindicatormethods.pdf)  \n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\r\n<link href=\"../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/datatables-binding-0.31/datatables.js\"></script>\r\n<script src=\"../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\r\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\r\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\r\n<link href=\"../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}